name: Crowdin download

on:
  schedule:
    - cron: '0 * * * *' # hourly
  workflow_dispatch: # manually

jobs:
  download-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup

      - run: "yarn i18n:extract"

      - uses: crowdin/github-action@1.4.8
        with:
          upload_sources: false
          download_translations: true
          create_pull_request: false
          localization_branch_name: main
          commit_message: "chore(i18n): download translations from crowdin [skip ci]"
          source: 'src/locales/en-US.po'
          translation: 'src/locales/%locale%.po'
          crowdin_branch_name: widgets
          token: ${{ secrets.CROWDIN_TOKEN }}
          project_id: 458284
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
